version: '3'

vars:
  REGISTRY: ghost-core
  GIT_HASH:
    sh: git rev-parse --short HEAD || echo "dev"
  BUILD_DATE:
    sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
# ==========================================
# NGINX Settings
# ==========================================
  NGINX_VER: 1.28.1
  NGINX_SHA: "40e7a0916d121e8905ef50f2a738b675599e42b2224a582dd938603fed15788e"
  NJS_VER: 0.9.4
  NJS_SHA: "7b3a9f14b0f09311d9031c2a252cb0e23c06baac2e586a7d12c75aa6cba4ca0e"
# ==========================================
# Redis Settings
# ==========================================
  REDIS_VER: 8.4.0
  REDIS_SHA: "b947d9015622669b5bee8ec954f658b3278d42dbefae23a92d9b7704bfe143f9"
# ==========================================
# postgres Settings
# ==========================================
  POSTGRES_VER: 17.7
  POSTGRES_SHA: "4a9e94204e265b292b0b36534c38543f24f9d96f5413ceac489ef053082ae752"


tasks:
  default:
    deps: [nginx:build-all]

  # ==========================================
  # BUILD TASKS
  # ==========================================

  nginx:build-all:
    desc: Build all Nginx variants (Lite & NJS)
    deps: [nginx:lite, nginx:njs]

  nginx:lite:
    desc: Build Nginx Lite (Distroless)
    cmds:
      - echo ">>> Building Ghost Core [Nginx Lite]..."
      - >
        docker build --no-cache --target final
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-lite
        -f nginx/Dockerfile .

  nginx:njs:
    desc: Build Nginx NJS (Distroless)
    cmds:
      - echo ">>> Building Ghost Core [Nginx NJS]..."
      - >
        docker build --no-cache --target final
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg NJS_VERSION={{.NJS_VER}}
        --build-arg NJS_SHA256={{.NJS_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/nginx:njs
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-njs
        -f nginx/Dockerfile .

  nginx:dev:
    desc: Build Nginx Dev (Bash/Tools)
    cmds:
      - echo ">>> Building Ghost Core [Nginx Dev]..."
      - >
        docker build --no-cache --target dev
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg NJS_VERSION={{.NJS_VER}}
        --build-arg NJS_SHA256={{.NJS_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-dev
        -f nginx/Dockerfile .


  nginx:run-dev:
    desc: Run Dev container interactively (Port 8080)
    interactive: true
    cmds:
      - echo ">>> Stopping old container..."
      - docker rm -f ghost-nginx-dev 2>/dev/null || true
      - echo ">>> Starting Ghost Core Dev..."
      - echo ">>> You are now entering the matrix. Try 'ls -l /usr/lib/nginx/modules'"
      - docker run -it --rm --name ghost-nginx-dev -p 8080:8080 {{.REGISTRY}}/nginx:{{.NGINX_VER}}-dev bash

  redis:prod:
    desc: Build Redis Production (Distroless)
    cmds:
      - echo ">>> Building Ghost Core [Redis Prod]..."
      - >
        docker build --no-cache --target final
        --build-arg REDIS_VERSION={{.REDIS_VER}}
        --build-arg REDIS_SHA256={{.REDIS_SHA}}
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/redis:{{.REDIS_VER}}
        -f redis/Dockerfile .

  redis:dev:
    desc: Build Redis Dev (Bash/Tools)
    cmds:
      - echo ">>> Building Ghost Core [Redis Dev]..."
      - >
        docker build --no-cache --target dev
        --build-arg REDIS_VERSION={{.REDIS_VER}}
        --build-arg REDIS_SHA256={{.REDIS_SHA}}
        -t {{.REGISTRY}}/redis:{{.REDIS_VER}}-dev
        -f redis/Dockerfile .

  redis:run-dev:
    desc: Run Redis Dev container interactively
    interactive: true
    cmds:
      - echo ">>> Stopping old Redis container..."
      - docker rm -f ghost-redis-dev 2>/dev/null || true
      - echo ">>> Starting Ghost Core Redis Dev..."
      - docker run -it --privileged=true --rm --name ghost-redis-dev -p 6379:6379 {{.REGISTRY}}/redis:{{.REDIS_VER}}-dev

  postgres:prod:
    desc: Build PostgreSQL Production (Distroless)
    cmds:
      - echo ">>> Building Ghost Core [PostgreSQL Prod]..."
      - >
        docker build --no-cache --target final
        --build-arg PG_VERSION={{.POSTGRES_VER}}
        --build-arg PG_SHA256={{.POSTGRES_SHA}}
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/postgres:{{.POSTGRES_VER}}
        -f postgres/Dockerfile .

  postgres:dev:
    desc: Build PostgreSQL Dev (Bash/Tools)
    cmds:
      - echo ">>> Building Ghost Core [PostgreSQL Dev]..."
      - >
        docker build --no-cache --target dev
        --build-arg PG_VERSION={{.POSTGRES_VER}}
        --build-arg PG_SHA256={{.POSTGRES_SHA}}
        -t {{.REGISTRY}}/postgres:{{.POSTGRES_VER}}-dev
        -f postgres/Dockerfile .

  postgres:run-dev:
    desc: Run PostgreSQL Dev container interactively
    interactive: true
    cmds:
      - echo ">>> Stopping old PostgreSQL container..."
      - docker rm -f ghost-postgres-dev 2>/dev/null || true
      - echo ">>> Starting Ghost Core PostgreSQL Dev..."
      - >
        docker run -it --rm 
        --name ghost-postgres-dev 
        -p 5432:5432 
        -v pg_data:/var/lib/postgresql/data 
        {{.REGISTRY}}/postgres:{{.POSTGRES_VER}}-dev
