version: '3'

vars:
  REGISTRY: ghost-core
  GIT_HASH:
    sh: git rev-parse --short HEAD || echo "dev"
  BUILD_DATE:
    sh: date -u +'%Y-%m-%dT%H:%M:%SZ'
# ==========================================
# NGINX Settings
# ==========================================
  NGINX_VER: 1.29.4
  NGINX_SHA: "5a7d37eee505866fbab5810fa9f78247d6d5d9157a595c4e7a72043141ddab25"
  NJS_VER: 0.9.4
  NJS_SHA: "7b3a9f14b0f09311d9031c2a252cb0e23c06baac2e586a7d12c75aa6cba4ca0e"
# ==========================================
# Redis Settings
# ==========================================
  REDIS_VER: 8.4.0
  REDIS_SHA: "b947d9015622669b5bee8ec954f658b3278d42dbefae23a92d9b7704bfe143f9"


tasks:    
  nginx:build-all:
    desc: Build ALL variants (Light, Full, Extras) + Dev versions
    deps: 
      - nginx:light
      - nginx:full
      - nginx:extras
      - nginx:light-dev
      - nginx:full-dev
      - nginx:extras-dev

  # ============================================================================
  # 1. LIGHT FLAVOR (Core only, minimal size)
  # ============================================================================
  nginx:light:
    desc: Build Nginx Light (Distroless) - Core features only
    cmds:
      - echo ">>> Building [Nginx Light] (Distroless)..."
      - >
        docker build --no-cache --target final
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg BUILD_MODE=core
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-core
        -t {{.REGISTRY}}/nginx:light
        -f nginx/Dockerfile .

  nginx:light-dev:
    desc: Build Nginx Light (Dev) - With Bash & Tools
    cmds:
      - echo ">>> Building [Nginx Light] (Dev)..."
      - >
        docker build --no-cache --target dev
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg BUILD_MODE=core
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-core-dev
        -f nginx/Dockerfile .

  # ============================================================================
  # 2. FULL FLAVOR (Standard, includes Stream, Mail, NJS)
  # ============================================================================
  nginx:full:
    desc: Build Nginx Full (Distroless) - Standard features
    cmds:
      - echo ">>> Building [Nginx Full] (Distroless)..."
      - >
        docker build --no-cache --target final
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg BUILD_MODE=full
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-full
        -t {{.REGISTRY}}/nginx:full
        -t {{.REGISTRY}}/nginx:latest
        -f nginx/Dockerfile .

  nginx:full-dev:
    desc: Build Nginx Full (Dev) - With Bash & Tools
    cmds:
      - echo ">>> Building [Nginx Full] (Dev)..."
      - >
        docker build --no-cache --target dev
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg BUILD_MODE=full
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-full-dev
        -f nginx/Dockerfile .

  # ============================================================================
  # 3. EXTRAS FLAVOR (Heavy, includes Images, XML, Brotli, Headers-More)
  # ============================================================================
  nginx:extras:
    desc: Build Nginx Extras (Distroless) - All Modules
    cmds:
      - echo ">>> Building [Nginx Extras] (Distroless)..."
      - >
        docker build --no-cache --target final
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg BUILD_MODE=extras
        --build-arg VCS_REF={{.GIT_HASH}}
        --build-arg BUILD_DATE={{.BUILD_DATE}}
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-extras
        -t {{.REGISTRY}}/nginx:extras
        -f nginx/Dockerfile .

  nginx:extras-dev:
    desc: Build Nginx Extras (Dev) - With Bash & Tools
    cmds:
      - echo ">>> Building [Nginx Extras] (Dev)..."
      - >
        docker build --no-cache --target dev
        --build-arg NGINX_VERSION={{.NGINX_VER}}
        --build-arg NGINX_SHA256={{.NGINX_SHA}}
        --build-arg CONFIG_FILE=nginx.conf
        --build-arg BUILD_MODE=extras
        -t {{.REGISTRY}}/nginx:{{.NGINX_VER}}-extras-dev
        -f nginx/Dockerfile .

  # ============================================================================
  # UTILS
  # ============================================================================
  nginx:run-dev:
    desc: Run the FULL Nginx Dev container interactively (Port 8080)
    interactive: true
    cmds:
      - >
        echo ">>> Stopping old container..." &&
        docker rm -f ghost-nginx-dev 2>/dev/null || true
      - >
        echo ">>> Starting Ghost Core Dev (Full Flavor)..." &&
        echo ">>> Check modules: ls -l /usr/lib/nginx/modules" &&
        docker run -it --rm --name ghost-nginx-dev -p 8080:8080 {{.REGISTRY}}/nginx:{{.NGINX_VER}}-full-dev bash

  redis:dev:
    desc: Build Redis Dev (With Tools)
    cmds:
      - echo ">>> Building Ghost Core [Redis Dev]..."
      - >
        docker build --no-cache --target dev
        --build-arg REDIS_VERSION={{.REDIS_VER}}
        --build-arg REDIS_SHA256={{.REDIS_SHA}}
        -t {{.REGISTRY}}/redis:dev
        -t {{.REGISTRY}}/redis:{{.REDIS_VER}}-dev
        -f redis/Dockerfile .

  redis:run-dev:
    desc: Run Redis Dev interactively
    interactive: true
    cmds:
      - echo ">>> Stopping old Redis container..."
      - docker rm -f ghost-redis-dev 2>/dev/null || true
      - echo ">>> Starting Ghost Core Redis Dev (with SYS_ADMIN cap for tuning)..."
      - >
        docker run -i --rm \
          --name ghost-redis-dev \
          --privileged \
          -p 6379:6379 \
          {{.REGISTRY}}/redis:{{.REDIS_VER}}-dev \
          
