mkdir -p /rootfs/etc/nginx
CONF_FILE="/rootfs/etc/nginx/modules.conf"
MODULES_DIR="/usr/lib/nginx/modules"

echo "# Auto-generated by build.sh based on mode: $MODE" > "$CONF_FILE"

PRIORITY_MODULES="ngx_stream_module.so ngx_mail_module.so"

BUFFER_PRIORITY=""
BUFFER_NORMAL=""

for so in /rootfs/usr/lib/nginx/modules/*.so; do
    [ -e "$so" ] || continue
    FILENAME=$(basename "$so")
    LOAD_LINE="load_module $MODULES_DIR/$FILENAME;"
    
    IS_PRIORITY=0
    for p_mod in $PRIORITY_MODULES; do
        if [ "$FILENAME" == "$p_mod" ]; then
            IS_PRIORITY=1
            break
        fi
    done

    if [ $IS_PRIORITY -eq 1 ]; then
        BUFFER_PRIORITY="${BUFFER_PRIORITY}${LOAD_LINE}\n"
    else
        BUFFER_NORMAL="${BUFFER_NORMAL}${LOAD_LINE}\n"
    fi
done

if [ -n "$BUFFER_PRIORITY" ]; then
    printf "$BUFFER_PRIORITY" >> "$CONF_FILE"
fi

if [ -n "$BUFFER_NORMAL" ]; then
    printf "$BUFFER_NORMAL" >> "$CONF_FILE"
fi

if [ -f "/rootfs/usr/lib/nginx/modules/ngx_http_perl_module.so" ]; then
    mkdir -p /rootfs/usr/lib /rootfs/usr/share /rootfs/usr/local/lib /rootfs/usr/local/share

    if [ -d "/usr/lib/perl5" ]; then
        cp -a /usr/lib/perl5 /rootfs/usr/lib/
    fi
    
    if [ -d "/usr/share/perl5" ]; then
        cp -a /usr/share/perl5 /rootfs/usr/share/
    fi
fi

ln -sf /dev/stdout /rootfs/var/log/nginx/access.log
ln -sf /dev/stderr /rootfs/var/log/nginx/error.log